---
apiVersion: v1
kind: ConfigMap
data:
  APP_NAME: "pingpong-app"
  PORT: "5000"
metadata:
  name: env-pingping-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-deploy
spec:
  selector:
    matchLabels:
      app: pingpong-app
  replicas: 3
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app-container
          image: arifh19/pingpong-app:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: env-pingping-app
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-service
spec:
  selector:
    app: pingpong-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pingpong-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: pingpong-app-service
              servicePort: 80

    - host: pingpong.me
      http:
        paths:
          - backend:
              serviceName: pingpong-app-service
              servicePort: 80
